# Generated by Django 5.2 on 2025-04-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='porcentaje_derecho_autoral',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
