# Generated by Django 5.2 on 2025-04-22 23:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_audio_porcentaje_derecho_autoral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
