# Generated by Django 5.2 on 2025-04-22 23:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_alter_audio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='archivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
