# Generated by Django 5.2 on 2025-04-22 23:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0004_alter_audio_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='archivo',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
