# Generated by Django 5.2 on 2025-04-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0005_alter_audio_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='porcentaje_derecho_autoral',
            new_name='derechos_autor',
        ),
    ]
